// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported for this target.');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtEL5SgzdV3NXa6w2NokGMY8R8Wsc48h0',
    appId: '1:569898989301:android:24260da7563d0667b5b7bc',
    messagingSenderId: '569898989301',
    projectId: 'loginsignupdemo-dc440',
    databaseURL: 'https://loginsignupdemo-dc440-default-rtdb.firebaseio.com',
    storageBucket: 'loginsignupdemo-dc440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ60zTcW46zrDV76AM_b8PGosSqea12BY',
    appId: '1:569898989301:ios:56e8ec7b1099ebb9b5b7bc',
    messagingSenderId: '569898989301',
    projectId: 'loginsignupdemo-dc440',
    databaseURL: 'https://loginsignupdemo-dc440-default-rtdb.firebaseio.com',
    storageBucket: 'loginsignupdemo-dc440.appspot.com',
    iosBundleId: 'com.demo.loginsignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ60zTcW46zrDV76AM_b8PGosSqea12BY',
    appId: '1:569898989301:ios:b14920d07d4c8e8db5b7bc',
    messagingSenderId: '569898989301',
    projectId: 'loginsignupdemo-dc440',
    databaseURL: 'https://loginsignupdemo-dc440-default-rtdb.firebaseio.com',
    storageBucket: 'loginsignupdemo-dc440.appspot.com',
    iosBundleId: 'com.example.takeHomeAssignment',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm93QfzdqJOhAbuRV-Ek7cVvVJ8kh2_L8',
    appId: '1:569898989301:web:aa2e9ea6d8cbd402b5b7bc',
    messagingSenderId: '569898989301',
    projectId: 'loginsignupdemo-dc440',
    authDomain: 'loginsignupdemo-dc440.firebaseapp.com',
    databaseURL: 'https://loginsignupdemo-dc440-default-rtdb.firebaseio.com',
    storageBucket: 'loginsignupdemo-dc440.appspot.com',
    measurementId: 'G-NN76XPMC42',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm93QfzdqJOhAbuRV-Ek7cVvVJ8kh2_L8',
    appId: '1:569898989301:web:65d5c99512d44aa2b5b7bc',
    messagingSenderId: '569898989301',
    projectId: 'loginsignupdemo-dc440',
    authDomain: 'loginsignupdemo-dc440.firebaseapp.com',
    databaseURL: 'https://loginsignupdemo-dc440-default-rtdb.firebaseio.com',
    storageBucket: 'loginsignupdemo-dc440.appspot.com',
    measurementId: 'G-09DMDN1DW3',
  );

}