// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_task_board/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i11;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i12;
import 'package:flutter_task_board/core/sync_service.dart' as _i13;
import 'package:flutter_task_board/features/auth/domain/auth_repository.dart'
    as _i9;
import 'package:flutter_task_board/features/auth/domain/user.dart' as _i2;
import 'package:flutter_task_board/features/board/domain/board.dart' as _i8;
import 'package:flutter_task_board/features/board/domain/board_repository.dart'
    as _i7;
import 'package:flutter_task_board/features/task/data/realtime_database_repository.dart'
    as _i10;
import 'package:flutter_task_board/features/task/domain/comment_entity.dart'
    as _i6;
import 'package:flutter_task_board/features/task/domain/task_entity.dart'
    as _i5;
import 'package:flutter_task_board/features/task/domain/task_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthUser_0 extends _i1.SmartFake implements _i2.AuthUser {
  _FakeAuthUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.TaskEntity>> watchTasks(String? boardId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTasks, [boardId]),
            returnValue: _i4.Stream<List<_i5.TaskEntity>>.empty(),
          )
          as _i4.Stream<List<_i5.TaskEntity>>);

  @override
  _i4.Future<void> createTask(_i5.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateTask(_i5.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i6.CommentEntity>> watchComments(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#watchComments, [taskId]),
            returnValue: _i4.Stream<List<_i6.CommentEntity>>.empty(),
          )
          as _i4.Stream<List<_i6.CommentEntity>>);

  @override
  _i4.Future<void> addComment(_i6.CommentEntity? comment) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [comment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BoardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoardRepository extends _i1.Mock implements _i7.BoardRepository {
  MockBoardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i8.Board>> watchBoards() =>
      (super.noSuchMethod(
            Invocation.method(#watchBoards, []),
            returnValue: _i4.Stream<List<_i8.Board>>.empty(),
          )
          as _i4.Stream<List<_i8.Board>>);

  @override
  _i4.Future<void> createBoard(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#createBoard, [title]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBoard(_i8.Board? board) =>
      (super.noSuchMethod(
            Invocation.method(#updateBoard, [board]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBoard(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBoard, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.AuthUser?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i2.AuthUser?>.empty(),
          )
          as _i4.Stream<_i2.AuthUser?>);

  @override
  _i4.Future<_i2.AuthUser> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i4.Future<_i2.AuthUser>.value(
              _FakeAuthUser_0(
                this,
                Invocation.method(#signIn, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthUser>);

  @override
  _i4.Future<_i2.AuthUser> signUp(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [email, password]),
            returnValue: _i4.Future<_i2.AuthUser>.value(
              _FakeAuthUser_0(
                this,
                Invocation.method(#signUp, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthUser>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [RealtimeDatabaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeDatabaseRepository extends _i1.Mock
    implements _i10.RealtimeDatabaseRepository {
  MockRealtimeDatabaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> pushBoard(_i8.Board? board) =>
      (super.noSuchMethod(
            Invocation.method(#pushBoard, [board]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBoard(String? boardId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBoard, [boardId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i8.Board>> watchRemoteBoards() =>
      (super.noSuchMethod(
            Invocation.method(#watchRemoteBoards, []),
            returnValue: _i4.Stream<List<_i8.Board>>.empty(),
          )
          as _i4.Stream<List<_i8.Board>>);

  @override
  _i4.Future<void> pushTask(_i5.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#pushTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.TaskEntity>> watchRemoteTasks(String? boardId) =>
      (super.noSuchMethod(
            Invocation.method(#watchRemoteTasks, [boardId]),
            returnValue: _i4.Stream<List<_i5.TaskEntity>>.empty(),
          )
          as _i4.Stream<List<_i5.TaskEntity>>);

  @override
  _i4.Future<void> pushComment(_i6.CommentEntity? comment) =>
      (super.noSuchMethod(
            Invocation.method(#pushComment, [comment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i6.CommentEntity>> watchRemoteComments(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#watchRemoteComments, [taskId]),
            returnValue: _i4.Stream<List<_i6.CommentEntity>>.empty(),
          )
          as _i4.Stream<List<_i6.CommentEntity>>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i11.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i12.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i4.Stream<List<_i12.ConnectivityResult>>.empty(),
          )
          as _i4.Stream<List<_i12.ConnectivityResult>>);

  @override
  _i4.Future<List<_i12.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i4.Future<List<_i12.ConnectivityResult>>.value(
              <_i12.ConnectivityResult>[],
            ),
          )
          as _i4.Future<List<_i12.ConnectivityResult>>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i13.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void subscribeToBoardTasks(String? boardId) => super.noSuchMethod(
    Invocation.method(#subscribeToBoardTasks, [boardId]),
    returnValueForMissingStub: null,
  );

  @override
  void unsubscribeFromBoardTasks() => super.noSuchMethod(
    Invocation.method(#unsubscribeFromBoardTasks, []),
    returnValueForMissingStub: null,
  );

  @override
  void subscribeToTaskComments(String? taskId) => super.noSuchMethod(
    Invocation.method(#subscribeToTaskComments, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void unsubscribeFromTaskComments() => super.noSuchMethod(
    Invocation.method(#unsubscribeFromTaskComments, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
